# Site settings
name: 심유경
email: dbrud0904@gmail.com
author: yukyung Shim
url: https://yukyung-shim.github.io/
resume_site: 
github: https://github.com/yukyung-shim/
baseurl: "/"
description: developer shim
meta_description: 
motto: 
banner: 

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: yukyung-shim

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

